In [7]:
import pandas as pd
import numpy as np

import pandas as pd
from collections import Counter

from nltk.tokenize import sent_tokenize, word_tokenize, regexp_tokenize
from nltk.tokenize import regexp_tokenize
from nltk.corpus import stopwords

from nltk.stem import PorterStemmer, WordNetLemmatizer

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import classification_report, confusion_matrix

from datasets import Dataset
from transformers import DistilBertTokenizerFast, DistilBertForSequenceClassification
from transformers import TrainingArguments, Trainer

from peft import get_peft_model, LoraConfig, TaskType
import gensim
from gensim import corpora
from gensim.models.ldamulticore import LdaMulticore
import pyLDAvis.gensim_models
import pyLDAvis

import nltk
nltk.download('punkt')

import nltk
nltk.download('wordnet')


[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\lexil\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\lexil\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [8]:
lemmatizer = WordNetLemmatizer()
stop_words = set(stopwords.words('english'))

def preprocess(text_description):
    text_description = text_description.lower()
    text_description = text_description.translate(str.maketrans('', '', string.punctuation))
    tokens = word_tokenize(text_description)
    tokens = [lemmatizer.lemmatize(word) for word in tokens if word not in stop_words]
    return " ".join(tokens)

In [9]:
allbooksprocessed = pd.read_csv('../data/allbooksprocessed.csv')
allbooksprocessed

title                                        description  \
0         the silver chair  two english children undergo hairraising adven...   
1        a game of thrones                                       fantasyroman   
2               fablehaven  when kendra and seth go to stay at their grand...   
3     a wizard of earthsea  originally published in 1968 ursula k le guins...   
4                 lodestar  betrayed by one of their closest allies sophie...   
..                     ...                                                ...   
776  out of the everywhere  topics include astronomy humanity radiation ma...   
777         quantum shorts  this book presents winning and shortlisted sto...   
778          novel science  novel science is the first indepth study of th...   
779      fantastic voyages  by revealing the facts behind the fiction of s...   
780             holy scifi  can a computer have a soul are religion and sc...   

               genre  published_date  \
0            fantasy            1998   
1            fantasy            2011   
2            fantasy            2007   
3            fantasy            2012   
4            fantasy            2017   
..               ...             ...   
776  science fiction            1990   
777  science fiction            2019   
778  science fiction            2013   
779  science fiction            2006   
780  science fiction            2014   

                                            authors  \
0                               clive staples lewis   
1                                 george r r martin   
2                                      brandon mull   
3                                  ursula k le guin   
4                                 shannon messenger   
..                                              ...   
776                                    isaac asimov   
777          michael brooks jenny hogan puah xin yi   
778                                adelene buckland   
779  leroy w dubeck suzanne e moshier judith e boss   
780                                    paul j nahin   

                                 processed_description  
0    two english child undergo hairraising adventur...  
1                                         fantasyroman  
2    kendra seth go stay grandparent estate discove...  
3    originally published 1968 ursula k le guins wi...  
4    betrayed one closest ally sophies whole world ...  
..                                                 ...  
776  topic include astronomy humanity radiation mag...  
777  book present winning shortlisted story past ed...  
778  novel science first indepth study shocking gro...  
779  revealing fact behind fiction finest film scif...  
780  computer soul religion science mutually exclus...  

[781 rows x 6 columns]

In [10]:
X = allbooksprocessed['processed_description']
y = allbooksprocessed['genre']

X_train, X_test, y_train, y_test = train_test_split(X, y, stratify=y, test_size=0.2, random_state=42)

In [11]:
vectorizer = TfidfVectorizer(max_features=5000)
X_train_tfidf = vectorizer.fit_transform(X_train)
X_test_tfidf = vectorizer.transform(X_test)

In [12]:
model = LogisticRegression(max_iter=1000)
model.fit(X_train_tfidf, y_train)

LogisticRegression(max_iter=1000)

In [13]:
y_pred = model.predict(X_test_tfidf)

print("Classification Report:\n", classification_report(y_test, y_pred))
print(f'Accuracy: {accuracy_score(y_test, y_pred)}')
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))


Classification Report:
                     precision    recall  f1-score   support

           fantasy       0.85      0.63      0.72        27
historical fiction       0.78      0.28      0.41        25
           mystery       0.72      0.70      0.71        33
           romance       0.52      0.81      0.63        37
   science fiction       0.84      0.91      0.88        35

          accuracy                           0.69       157
         macro avg       0.74      0.67      0.67       157
      weighted avg       0.73      0.69      0.68       157

Accuracy: 0.6942675159235668
Confusion Matrix:
 [[17  1  1  7  1]
 [ 2  7  1 14  1]
 [ 0  0 23  6  4]
 [ 0  1  6 30  0]
 [ 1  0  1  1 32]]


In [14]:
feature_names = vectorizer.get_feature_names_out()
coefs = model.coef_

for i, genre in enumerate(model.classes_):
    top_features = np.argsort(coefs[i])[-10:]  # Top 10 features
    print(f"Top words in {genre}: {[feature_names[j] for j in top_features]}")

Top words in fantasy: ['world', 'narnia', 'six', 'edition', 'moomins', 'prince', 'magical', 'wizard', 'oz', 'adventure']
Top words in historical fiction: ['soon', 'tribe', 'love', 'author', 'woman', 'london', 'young', 'life', 'family', 'war']
Top words in mystery: ['miss', 'wife', 'nancy', 'crime', 'marple', 'killer', 'death', 'fantasyroman', 'mystery', 'murder']
Top words in romance: ['town', 'beach', 'shes', 'arrangement', 'york', 'price', 'romantic', 'bestselling', 'heart', 'love']
Top words in science fiction: ['form', 'explores', 'literature', 'space', 'literary', 'study', 'work', 'future', 'fiction', 'science']


In [15]:
vect = CountVectorizer(max_features=5000)
X_train_count = vectorizer.fit_transform(X_train)
X_test_count = vectorizer.transform(X_test)

In [16]:
nb = MultinomialNB().fit(X_train_count, y_train)

y_pred = nb.predict(X_test_count)

In [17]:
print(f'Accuracy: {accuracy_score(y_test, y_pred)}')
print(confusion_matrix(y_test, y_pred))

Accuracy: 0.6369426751592356
[[11  0  1 11  4]
 [ 1  2  0 19  3]
 [ 0  0 22  7  4]
 [ 0  1  3 32  1]
 [ 1  0  1  0 33]]


In [18]:
feature_names = vectorizer.get_feature_names_out()
coefs = model.coef_

for i, genre in enumerate(model.classes_):
    top_features = np.argsort(coefs[i])[-10:] 
    print(f"Top words in {genre}: {[feature_names[j] for j in top_features]}")

Top words in fantasy: ['world', 'narnia', 'six', 'edition', 'moomins', 'prince', 'magical', 'wizard', 'oz', 'adventure']
Top words in historical fiction: ['soon', 'tribe', 'love', 'author', 'woman', 'london', 'young', 'life', 'family', 'war']
Top words in mystery: ['miss', 'wife', 'nancy', 'crime', 'marple', 'killer', 'death', 'fantasyroman', 'mystery', 'murder']
Top words in romance: ['town', 'beach', 'shes', 'arrangement', 'york', 'price', 'romantic', 'bestselling', 'heart', 'love']
Top words in science fiction: ['form', 'explores', 'literature', 'space', 'literary', 'study', 'work', 'future', 'fiction', 'science']


In [19]:
allbooksprocessed

title                                        description  \
0         the silver chair  two english children undergo hairraising adven...   
1        a game of thrones                                       fantasyroman   
2               fablehaven  when kendra and seth go to stay at their grand...   
3     a wizard of earthsea  originally published in 1968 ursula k le guins...   
4                 lodestar  betrayed by one of their closest allies sophie...   
..                     ...                                                ...   
776  out of the everywhere  topics include astronomy humanity radiation ma...   
777         quantum shorts  this book presents winning and shortlisted sto...   
778          novel science  novel science is the first indepth study of th...   
779      fantastic voyages  by revealing the facts behind the fiction of s...   
780             holy scifi  can a computer have a soul are religion and sc...   

               genre  published_date  \
0            fantasy            1998   
1            fantasy            2011   
2            fantasy            2007   
3            fantasy            2012   
4            fantasy            2017   
..               ...             ...   
776  science fiction            1990   
777  science fiction            2019   
778  science fiction            2013   
779  science fiction            2006   
780  science fiction            2014   

                                            authors  \
0                               clive staples lewis   
1                                 george r r martin   
2                                      brandon mull   
3                                  ursula k le guin   
4                                 shannon messenger   
..                                              ...   
776                                    isaac asimov   
777          michael brooks jenny hogan puah xin yi   
778                                adelene buckland   
779  leroy w dubeck suzanne e moshier judith e boss   
780                                    paul j nahin   

                                 processed_description  
0    two english child undergo hairraising adventur...  
1                                         fantasyroman  
2    kendra seth go stay grandparent estate discove...  
3    originally published 1968 ursula k le guins wi...  
4    betrayed one closest ally sophies whole world ...  
..                                                 ...  
776  topic include astronomy humanity radiation mag...  
777  book present winning shortlisted story past ed...  
778  novel science first indepth study shocking gro...  
779  revealing fact behind fiction finest film scif...  
780  computer soul religion science mutually exclus...  

[781 rows x 6 columns]

In [20]:
allbooksprocessed = allbooksprocessed.rename(columns={"processed_description": "text", "genre": "label"})
allbooksprocessed['label'] = LabelEncoder().fit_transform(allbooksprocessed['label'])
allbooksprocessed


title                                        description  \
0         the silver chair  two english children undergo hairraising adven...   
1        a game of thrones                                       fantasyroman   
2               fablehaven  when kendra and seth go to stay at their grand...   
3     a wizard of earthsea  originally published in 1968 ursula k le guins...   
4                 lodestar  betrayed by one of their closest allies sophie...   
..                     ...                                                ...   
776  out of the everywhere  topics include astronomy humanity radiation ma...   
777         quantum shorts  this book presents winning and shortlisted sto...   
778          novel science  novel science is the first indepth study of th...   
779      fantastic voyages  by revealing the facts behind the fiction of s...   
780             holy scifi  can a computer have a soul are religion and sc...   

     label  published_date                                         authors  \
0        0            1998                             clive staples lewis   
1        0            2011                               george r r martin   
2        0            2007                                    brandon mull   
3        0            2012                                ursula k le guin   
4        0            2017                               shannon messenger   
..     ...             ...                                             ...   
776      4            1990                                    isaac asimov   
777      4            2019          michael brooks jenny hogan puah xin yi   
778      4            2013                                adelene buckland   
779      4            2006  leroy w dubeck suzanne e moshier judith e boss   
780      4            2014                                    paul j nahin   

                                                  text  
0    two english child undergo hairraising adventur...  
1                                         fantasyroman  
2    kendra seth go stay grandparent estate discove...  
3    originally published 1968 ursula k le guins wi...  
4    betrayed one closest ally sophies whole world ...  
..                                                 ...  
776  topic include astronomy humanity radiation mag...  
777  book present winning shortlisted story past ed...  
778  novel science first indepth study shocking gro...  
779  revealing fact behind fiction finest film scif...  
780  computer soul religion science mutually exclus...  

[781 rows x 6 columns]

In [21]:
num_labels = allbooksprocessed['label'].nunique()
num_labels


5

In [22]:
dataset = Dataset.from_pandas(allbooksprocessed)

In [23]:
dataset = dataset.train_test_split(test_size=0.2)

In [24]:
dataset['train']

Dataset({
    features: ['title', 'description', 'label', 'published_date', 'authors', 'text'],
    num_rows: 624
})

In [25]:
train_dataset = dataset['train']
test_dataset = dataset['test']

In [26]:
tokenizer = DistilBertTokenizerFast.from_pretrained("distilbert-base-uncased")

In [27]:
train_dataset = train_dataset.map(lambda df: tokenizer(df['text'], padding="max_length", truncation=True), batched=True)
test_dataset = test_dataset.map(lambda df: tokenizer(df['text'], padding="max_length", truncation=True), batched=True)

c:\Users\lexil\anaconda3\Lib\site-packages\datasets\utils\_dill.py:385: DeprecationWarning: co_lnotab is deprecated, use co_lines instead.
  obj.co_lnotab,  # for < python 3.10 [not counted in args]


Map:   0%|          | 0/624 [00:00<?, ? examples/s]

c:\Users\lexil\anaconda3\Lib\site-packages\datasets\utils\_dill.py:385: DeprecationWarning: co_lnotab is deprecated, use co_lines instead.
  obj.co_lnotab,  # for < python 3.10 [not counted in args]


Map:   0%|          | 0/157 [00:00<?, ? examples/s]

In [28]:
train_dataset.set_format("torch", columns=["input_ids", "attention_mask", "label"])
test_dataset.set_format("torch", columns=["input_ids", "attention_mask", "label"])

In [29]:
model = DistilBertForSequenceClassification.from_pretrained("distilbert-base-uncased", num_labels=num_labels)

Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight', 'pre_classifier.bias', 'pre_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


In [30]:
training = TrainingArguments(num_train_epochs = 5,
                            weight_decay = 0.01,
                            report_to = 'none')

In [31]:
training_object = Trainer(
    model = model,
    args = training,
    train_dataset = train_dataset
)

In [32]:
training_object.train()

c:\Users\lexil\anaconda3\Lib\site-packages\torch\utils\data\dataloader.py:665: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)
c:\Users\lexil\anaconda3\Lib\site-packages\executing\executing.py:713: DeprecationWarning: ast.Str is deprecated and will be removed in Python 3.14; use ast.Constant instead
  right=ast.Str(s=sentinel),
c:\Users\lexil\anaconda3\Lib\site-packages\executing\executing.py:713: DeprecationWarning: ast.Str is deprecated and will be removed in Python 3.14; use ast.Constant instead
  right=ast.Str(s=sentinel),
c:\Users\lexil\anaconda3\Lib\ast.py:587: DeprecationWarning: Attribute s is deprecated and will be removed in Python 3.14; use value instead
  return Constant(*args, **kwargs)
c:\Users\lexil\anaconda3\Lib\site-packages\executing\executing.py:713: DeprecationWarning: ast.Str is deprecated and will be removed in Python 3.14; use ast.Constant instead
  right=ast.Str(s=s

KeyboardInterrupt: 

In [ ]:
predicted = training_object.predict(test_dataset)

c:\Users\lexil\anaconda3\Lib\site-packages\torch\utils\data\dataloader.py:665: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)


In [ ]:
prediction_labels = predicted.predictions
true_labels = predicted.label_ids

In [ ]:
preds = np.argmax(predicted.predictions, axis=-1)

In [ ]:
print(confusion_matrix(true_labels, preds))
print(classification_report(true_labels, preds))

[[28  3  1  1  1]
 [ 1 12  2  5  0]
 [ 1  4 25  2  2]
 [ 1  3  1 24  0]
 [ 3  1  1  0 35]]
              precision    recall  f1-score   support

           0       0.82      0.82      0.82        34
           1       0.52      0.60      0.56        20
           2       0.83      0.74      0.78        34
           3       0.75      0.83      0.79        29
           4       0.92      0.88      0.90        40

    accuracy                           0.79       157
   macro avg       0.77      0.77      0.77       157
weighted avg       0.80      0.79      0.79       157



Fantasy - pretty strong, pretty distinct words. 
Historical fiction - worst performancce at 52% possible crossover with things like love, war, family  
Mystery - good, maybe crossover? (crime/love could be getting things mixed with romance or historical fiction perhaps.)
Romance - Good 
Sci-Fi  - best - likely because the vocabulary is pretty distinct?

Next steps - try getting more books? 
attempt to look at bi-grams 
topic modeling --  pi - LDA -vis
LoRA ?
Jaccard similarity between genres?

In [ ]:
def preprocess(text):
    tokens = word_tokenize(text.lower())
    return [token for token in tokens if token.isalpha() and token not in stop_words]

allbooksprocessed['processed_text'] = allbooksprocessed['text'].apply(preprocess)

In [ ]:
texts = allbooksprocessed['processed_text'].tolist()

dictionary = corpora.Dictionary(texts)
corpus = [dictionary.doc2bow(text) for text in texts]

In [35]:
num_topics = 5 

lda_model = LdaMulticore(corpus, num_topics=num_topics, id2word=dictionary, passes=10, workers=2)

for idx, topic in lda_model.print_topics(num_topics):
    print(f"Topic {idx}: {topic}")

Topic 0: 0.009*"book" + 0.007*"time" + 0.006*"story" + 0.005*"love" + 0.005*"life" + 0.004*"new" + 0.004*"fiction" + 0.003*"one" + 0.003*"travel" + 0.003*"first"
Topic 1: 0.004*"life" + 0.003*"man" + 0.003*"story" + 0.003*"novel" + 0.003*"time" + 0.003*"come" + 0.003*"find" + 0.003*"young" + 0.003*"world" + 0.002*"two"
Topic 2: 0.004*"new" + 0.004*"life" + 0.004*"fiction" + 0.004*"time" + 0.004*"one" + 0.004*"book" + 0.003*"year" + 0.003*"author" + 0.003*"love" + 0.003*"find"
Topic 3: 0.007*"new" + 0.007*"life" + 0.006*"one" + 0.005*"time" + 0.005*"love" + 0.005*"author" + 0.005*"world" + 0.004*"york" + 0.004*"book" + 0.004*"bestselling"
Topic 4: 0.022*"science" + 0.017*"fiction" + 0.006*"new" + 0.006*"world" + 0.005*"book" + 0.004*"future" + 0.004*"story" + 0.004*"life" + 0.003*"human" + 0.003*"work"


In [36]:
vis = pyLDAvis.gensim_models.prepare(lda_model, corpus, dictionary)
pyLDAvis.display(vis)